import db from "./db";

async function callDeepSeek(messages: { role: string; content: string }[], maxTokens = 4000) {
  const res = await fetch("https://api.deepseek.com/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${process.env.DEEPSEEK_API_KEY}`,
    },
    body: JSON.stringify({
      model: "deepseek-chat",
      messages,
      temperature: 0.8,
      response_format: { type: "json_object" },
      max_tokens: maxTokens,
    }),
  });
  if (!res.ok) throw new Error(`DeepSeek API error: ${res.status}`);
  const data = await res.json();
  return data.choices[0]?.message?.content || null;
}

export async function initBlogTable() {
  await db.execute(`
    CREATE TABLE IF NOT EXISTS blog_posts (
      id TEXT PRIMARY KEY,
      slug TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      excerpt TEXT NOT NULL,
      content TEXT NOT NULL,
      cover_image TEXT,
      tags TEXT DEFAULT '[]',
      meta_title TEXT,
      meta_description TEXT,
      published_at TEXT NOT NULL,
      created_at TEXT NOT NULL
    )
  `);
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImage: string | null;
  tags: string[];
  metaTitle: string;
  metaDescription: string;
  publishedAt: string;
  createdAt: string;
}

export async function getAllPosts(limit = 50): Promise<BlogPost[]> {
  await initBlogTable();
  const result = await db.execute({
    sql: `SELECT * FROM blog_posts ORDER BY published_at DESC LIMIT ?`,
    args: [limit],
  });

  return result.rows.map(rowToPost);
}

export async function getPostBySlug(slug: string): Promise<BlogPost | null> {
  await initBlogTable();
  const result = await db.execute({
    sql: `SELECT * FROM blog_posts WHERE slug = ?`,
    args: [slug],
  });

  if (result.rows.length === 0) return null;
  return rowToPost(result.rows[0]);
}

export async function getPostCount(): Promise<number> {
  await initBlogTable();
  const result = await db.execute(`SELECT COUNT(*) as count FROM blog_posts`);
  return result.rows[0].count as number;
}

function rowToPost(row: Record<string, unknown>): BlogPost {
  return {
    id: row.id as string,
    slug: row.slug as string,
    title: row.title as string,
    excerpt: row.excerpt as string,
    content: row.content as string,
    coverImage: row.cover_image as string | null,
    tags: JSON.parse((row.tags as string) || "[]"),
    metaTitle: (row.meta_title as string) || (row.title as string),
    metaDescription: (row.meta_description as string) || (row.excerpt as string),
    publishedAt: row.published_at as string,
    createdAt: row.created_at as string,
  };
}

// Each topic is shaped like a real search query (the way people actually type
// into Google / ChatGPT) and carries a distinctive `keyword` — the long-tail
// phrase the post should rank for. The keyword is used to (a) target on-page
// SEO and (b) reliably de-duplicate against already-published posts.
interface BlogTopic {
  query: string;
  keyword: string;
}

const BLOG_TOPICS: BlogTopic[] = [
  { query: "How do I find leaked API keys in a Next.js app?", keyword: "find leaked api keys" },
  { query: "Is code generated by Cursor secure?", keyword: "is cursor code secure" },
  { query: "How to fix XSS vulnerabilities in a Bolt.new app", keyword: "bolt.new xss vulnerability" },
  { query: "How to secure a Next.js app built with AI coding tools", keyword: "secure ai-generated next.js app" },
  { query: "Is v0 (Vercel) generated code safe to deploy?", keyword: "is v0 code safe" },
  { query: "How to scan a website for vulnerabilities for free", keyword: "free website vulnerability scanner" },
  { query: "How to find exposed secrets in client-side JavaScript", keyword: "exposed secrets in javascript" },
  { query: "How to prevent SQL injection in AI-generated code", keyword: "prevent sql injection ai code" },
  { query: "Is my Lovable.dev app leaking user data?", keyword: "lovable.dev data leak" },
  { query: "How to remove hardcoded secrets from v0 components", keyword: "hardcoded secrets v0" },
  { query: "OWASP Top 10 checklist for vibe-coded apps", keyword: "owasp top 10 vibe coding" },
  { query: "How to add input validation to AI-generated code", keyword: "input validation ai code" },
  { query: "Security checklist before launching a SaaS", keyword: "saas security checklist" },
  { query: "How to check npm dependencies for known CVEs", keyword: "check npm dependencies cve" },
  { query: "How to make your website appear in ChatGPT and Claude", keyword: "appear in chatgpt and claude" },
  { query: "How to add an llms.txt file to your website", keyword: "add llms.txt file" },
  { query: "What is Answer Engine Optimization (AEO)?", keyword: "what is answer engine optimization" },
  { query: "How to improve Core Web Vitals in a Next.js app", keyword: "improve core web vitals next.js" },
  { query: "How to add rate limiting to an indie SaaS API", keyword: "rate limiting saas api" },
  { query: "Do I need a security scan before deploying to Vercel?", keyword: "security scan before vercel deploy" },
  { query: "How should solo developers manage secrets and env vars?", keyword: "secrets management solo developer" },
  { query: "How to fix CORS misconfigurations in an API", keyword: "fix cors misconfiguration" },
  { query: "How to spot authentication bypass bugs in your app", keyword: "authentication bypass vulnerability" },
  { query: "Security scanning vs penetration testing: what's the difference?", keyword: "security scanning vs pentesting" },
  { query: "How an exposed .env file leads to account takeover", keyword: "exposed .env file risk" },
  { query: "How to prevent SSRF in AI-generated backend code", keyword: "prevent ssrf vulnerability" },
  { query: "How to add Content Security Policy headers to a Next.js app", keyword: "content security policy next.js" },
  { query: "How to secure webhook endpoints in a SaaS app", keyword: "secure webhook endpoints" },
  { query: "How to fix open redirect vulnerabilities in Next.js", keyword: "open redirect next.js" },
  { query: "Why AI coding tools skip security (and how to catch it)", keyword: "ai coding tools security risks" },

  // --- Per-tool security guides (capture every "is X safe / secure X" search) ---
  { query: "Is Replit Agent generated code secure?", keyword: "is replit agent code secure" },
  { query: "Is Windsurf (Codeium) generated code safe to ship?", keyword: "is windsurf code safe" },
  { query: "Are ChatGPT-generated apps secure?", keyword: "chatgpt generated app security" },
  { query: "Is code from Claude artifacts safe to deploy?", keyword: "claude artifacts security" },
  { query: "How to secure a Base44 app", keyword: "base44 app security" },
  { query: "How to secure a Replit-hosted app", keyword: "replit app security" },
  { query: "How to secure an app built with GitHub Copilot", keyword: "github copilot code security" },

  // --- Provider-specific secret leaks (high commercial intent) ---
  { query: "How to find a leaked Supabase service_role key", keyword: "leaked supabase service role key" },
  { query: "How to find a leaked Stripe secret key in your code", keyword: "leaked stripe secret key" },
  { query: "How to find a leaked OpenAI API key", keyword: "leaked openai api key" },
  { query: "How to fix an exposed Firebase API key", keyword: "exposed firebase api key" },
  { query: "What to do when your AWS access key is leaked", keyword: "leaked aws access key" },

  // --- Platform security configuration ---
  { query: "How to set up Supabase Row Level Security correctly", keyword: "supabase row level security" },
  { query: "How to write secure Firebase security rules", keyword: "firebase security rules" },
  { query: "How to store secrets safely in Vercel environment variables", keyword: "vercel environment variables secrets" },
  { query: "How to add authentication to a Next.js app the right way", keyword: "nextjs authentication best practices" },
  { query: "How to secure a Netlify-deployed site", keyword: "netlify site security" },

  // --- More OWASP / vulnerability classes ---
  { query: "What is IDOR and how do I fix it in my app?", keyword: "idor vulnerability fix" },
  { query: "How to prevent mass assignment vulnerabilities", keyword: "mass assignment vulnerability" },
  { query: "How to securely handle JWT tokens in a web app", keyword: "jwt security best practices" },
  { query: "How to prevent CSRF attacks in a SaaS app", keyword: "prevent csrf attack" },
  { query: "How to prevent path traversal vulnerabilities", keyword: "path traversal vulnerability" },
  { query: "What is prompt injection and how do I defend against it?", keyword: "prompt injection defense" },
  { query: "How to securely store passwords (hashing done right)", keyword: "secure password hashing" },
  { query: "How to prevent broken access control in your API", keyword: "broken access control fix" },

  // --- AEO / GEO (answer & generative engine optimization) ---
  { query: "How to rank in Google AI Overviews", keyword: "rank in google ai overviews" },
  { query: "How to get cited by Perplexity AI", keyword: "get cited by perplexity" },
  { query: "What is Generative Engine Optimization (GEO)?", keyword: "what is generative engine optimization" },
  { query: "How to add structured data (JSON-LD) to a Next.js site", keyword: "json-ld structured data nextjs" },
  { query: "robots.txt vs llms.txt: what's the difference?", keyword: "robots.txt vs llms.txt" },
  { query: "How to make your docs easy for AI to cite", keyword: "ai citable content" },

  // --- Commercial-intent comparisons & alternatives ---
  { query: "Snyk vs OverMCP: which security scanner should you use?", keyword: "snyk alternative vibe coding" },
  { query: "Best security scanners for indie hackers in 2025", keyword: "best security scanner indie hackers" },
  { query: "Free vs paid website security scanners compared", keyword: "free vs paid security scanner" },
  { query: "Semgrep vs automated AI security scanning", keyword: "semgrep alternative" },
  { query: "How much does a security audit cost for a small SaaS?", keyword: "saas security audit cost" },

  // --- Practical how-to (long-tail, high volume) ---
  { query: "How to check if my website has been hacked", keyword: "check if website hacked" },
  { query: "How to do a security audit of your own website", keyword: "diy website security audit" },
  { query: "How to add security headers to a Vercel deployment", keyword: "security headers vercel" },
  { query: "How to scan a GitHub repo for secrets", keyword: "scan github repo for secrets" },
  { query: "How to fix npm audit vulnerabilities", keyword: "fix npm audit vulnerabilities" },
  { query: "How to set up a Content Security Policy without breaking your site", keyword: "content security policy setup" },
  { query: "How to handle a data breach as a solo founder", keyword: "data breach response solo founder" },
  { query: "Pre-launch security checklist for AI-built MVPs", keyword: "pre-launch security checklist mvp" },
];

// When the curated BLOG_TOPICS pool is exhausted, ask the model to invent a
// fresh, specific, non-duplicate search query + primary keyword. This keeps the
// generation engine supplied indefinitely no matter how high the daily count is.
async function generateFreshTopic(existing: string[]): Promise<BlogTopic | null> {
  const content = await callDeepSeek(
    [
      {
        role: "system",
        content: `You are an SEO/AEO strategist for OverMCP (overmcp.com), a security scanner for "vibe-coded" apps built with AI tools (Cursor, Bolt.new, v0, Lovable, Replit Agent, Windsurf, GitHub Copilot, Claude, etc.).

Invent ONE fresh, highly specific, long-tail blog topic that real indie developers actually search on Google or ask ChatGPT/Perplexity. It must concern security, SEO, AEO/GEO, performance, dependency CVEs, or safe deployment of AI-built apps. It needs clear search intent and a distinctive primary keyword.

Return ONLY valid JSON:
{
  "query": "the exact natural-language search query a user would type",
  "keyword": "the distinctive long-tail primary keyword, lowercase, 2-6 words"
}`,
      },
      {
        role: "user",
        content: `Do NOT repeat or pick anything semantically similar to these already-covered topics:\n${
          existing.length ? existing.join("\n") : "none yet"
        }`,
      },
    ],
    400
  );
  if (!content) return null;
  try {
    const t = JSON.parse(content);
    if (t.query && t.keyword) {
      return { query: String(t.query), keyword: String(t.keyword) };
    }
  } catch {
    /* malformed JSON — caller falls back to the generic prompt */
  }
  return null;
}

export async function generateBlogPost(): Promise<BlogPost | null> {
  await initBlogTable();

  const existingResult = await db.execute(`SELECT title, slug FROM blog_posts`);
  const existingTitles = existingResult.rows.map((r) => r.title as string);
  const existingHaystack = existingResult.rows
    .map((r) => `${r.title as string} ${r.slug as string}`.toLowerCase())
    .join(" || ");

  const usedTopics = existingTitles.join(", ");
  // De-dupe on the distinctive keyword (not the first few words, which collide
  // across many "how to…" queries) so we don't regenerate covered topics.
  const topicPool = BLOG_TOPICS.filter(
    (t) => !existingHaystack.includes(t.keyword.toLowerCase())
  );

  // Prefer the curated, vetted pool. Once it's drained, fall back to AI-invented
  // fresh topics (retried a few times to avoid accidental duplicates) so a high
  // daily count never starves the engine or produces repeats.
  let suggestedTopic: BlogTopic | null =
    topicPool.length > 0
      ? topicPool[Math.floor(Math.random() * topicPool.length)]
      : null;

  if (!suggestedTopic) {
    for (let attempt = 0; attempt < 3; attempt++) {
      const fresh = await generateFreshTopic(existingTitles);
      if (fresh && !existingHaystack.includes(fresh.keyword.toLowerCase())) {
        suggestedTopic = fresh;
        break;
      }
    }
  }

  const content = await callDeepSeek([
    {
      role: "system",
      content: `You are an expert technical content writer for OverMCP (overmcp.com), a security scanning platform for "vibe-coded" apps — apps built quickly with AI coding tools like Cursor, Bolt.new, v0, Lovable, Replit Agent, etc.

Your audience: indie developers, solopreneurs, and makers who ship fast with AI but often skip security.

Write a blog post that:
1. Is 1000-1400 words
2. Directly and completely ANSWERS the search query it targets (this is what wins Google rankings and gets the post cited by ChatGPT/Claude/Perplexity)
3. Places the PRIMARY KEYWORD verbatim in: the title, the first 100 words, and at least one ## heading — naturally, never stuffed
4. Opens with a 2-3 sentence direct answer to the query (a "TL;DR" the searcher can act on immediately), then goes deeper
5. Provides genuine educational value: real examples, concrete code snippets, step-by-step fixes
6. Subtly positions OverMCP as the solution (mention it once, naturally — not salesy)
7. Uses markdown: ## headings, code blocks, bullet/numbered lists
8. ENDS with a "## FAQ" section containing 2-3 question/answer pairs (### Question then a short answer) — these win featured snippets and are easy for AI to extract
9. Includes a compelling meta title (under 60 chars) and meta description (under 155 chars), both containing the primary keyword

DO NOT write about topics already covered: ${usedTopics || "none yet"}

Return valid JSON:
{
  "title": "string (compelling, SEO-friendly, under 65 chars, contains the primary keyword)",
  "slug": "string (url-safe-kebab-case, derived from the primary keyword)",
  "excerpt": "string (1-2 sentences, hooks the reader, contains the primary keyword)",
  "content": "string (full markdown article, 1000-1400 words, ends with a ## FAQ section)",
  "tags": ["string", "string", "string"],
  "metaTitle": "string (under 60 chars, includes primary keyword)",
  "metaDescription": "string (under 155 chars, includes CTA)"
}`,
    },
    {
      role: "user",
      content: suggestedTopic
        ? `Write a blog post that answers this exact search query: "${suggestedTopic.query}"\nThe PRIMARY KEYWORD to target is: "${suggestedTopic.keyword}"`
        : `Write a blog post about a fresh security topic relevant to vibe-coded apps that hasn't been covered yet.`,
    },
  ]);
  if (!content) return null;

  const post = JSON.parse(content);
  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  await db.execute({
    sql: `INSERT INTO blog_posts (id, slug, title, excerpt, content, tags, meta_title, meta_description, published_at, created_at)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      id,
      post.slug,
      post.title,
      post.excerpt,
      post.content,
      JSON.stringify(post.tags || []),
      post.metaTitle || post.title,
      post.metaDescription || post.excerpt,
      now,
      now,
    ],
  });

  return {
    id,
    slug: post.slug,
    title: post.title,
    excerpt: post.excerpt,
    content: post.content,
    coverImage: null,
    tags: post.tags || [],
    metaTitle: post.metaTitle || post.title,
    metaDescription: post.metaDescription || post.excerpt,
    publishedAt: now,
    createdAt: now,
  };
}
