import db from "./db";

async function callDeepSeek(messages: { role: string; content: string }[], maxTokens = 4000) {
  const res = await fetch("https://api.deepseek.com/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${process.env.DEEPSEEK_API_KEY}`,
    },
    body: JSON.stringify({
      model: "deepseek-chat",
      messages,
      temperature: 0.8,
      response_format: { type: "json_object" },
      max_tokens: maxTokens,
    }),
  });
  if (!res.ok) throw new Error(`DeepSeek API error: ${res.status}`);
  const data = await res.json();
  return data.choices[0]?.message?.content || null;
}

export async function initBlogTable() {
  await db.execute(`
    CREATE TABLE IF NOT EXISTS blog_posts (
      id TEXT PRIMARY KEY,
      slug TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      excerpt TEXT NOT NULL,
      content TEXT NOT NULL,
      cover_image TEXT,
      tags TEXT DEFAULT '[]',
      meta_title TEXT,
      meta_description TEXT,
      published_at TEXT NOT NULL,
      created_at TEXT NOT NULL
    )
  `);
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImage: string | null;
  tags: string[];
  metaTitle: string;
  metaDescription: string;
  publishedAt: string;
  createdAt: string;
}

export async function getAllPosts(limit = 50): Promise<BlogPost[]> {
  await initBlogTable();
  const result = await db.execute({
    sql: `SELECT * FROM blog_posts ORDER BY published_at DESC LIMIT ?`,
    args: [limit],
  });

  return result.rows.map(rowToPost);
}

export async function getPostBySlug(slug: string): Promise<BlogPost | null> {
  await initBlogTable();
  const result = await db.execute({
    sql: `SELECT * FROM blog_posts WHERE slug = ?`,
    args: [slug],
  });

  if (result.rows.length === 0) return null;
  return rowToPost(result.rows[0]);
}

export async function getPostCount(): Promise<number> {
  await initBlogTable();
  const result = await db.execute(`SELECT COUNT(*) as count FROM blog_posts`);
  return result.rows[0].count as number;
}

function rowToPost(row: Record<string, unknown>): BlogPost {
  return {
    id: row.id as string,
    slug: row.slug as string,
    title: row.title as string,
    excerpt: row.excerpt as string,
    content: row.content as string,
    coverImage: row.cover_image as string | null,
    tags: JSON.parse((row.tags as string) || "[]"),
    metaTitle: (row.meta_title as string) || (row.title as string),
    metaDescription: (row.meta_description as string) || (row.excerpt as string),
    publishedAt: row.published_at as string,
    createdAt: row.created_at as string,
  };
}

// Each topic is shaped like a real search query (the way people actually type
// into Google / ChatGPT) and carries a distinctive `keyword` — the long-tail
// phrase the post should rank for. The keyword is used to (a) target on-page
// SEO and (b) reliably de-duplicate against already-published posts.
interface BlogTopic {
  query: string;
  keyword: string;
}

const BLOG_TOPICS: BlogTopic[] = [
  { query: "How do I find leaked API keys in a Next.js app?", keyword: "find leaked api keys" },
  { query: "Is code generated by Cursor secure?", keyword: "is cursor code secure" },
  { query: "How to fix XSS vulnerabilities in a Bolt.new app", keyword: "bolt.new xss vulnerability" },
  { query: "How to secure a Next.js app built with AI coding tools", keyword: "secure ai-generated next.js app" },
  { query: "Is v0 (Vercel) generated code safe to deploy?", keyword: "is v0 code safe" },
  { query: "How to scan a website for vulnerabilities for free", keyword: "free website vulnerability scanner" },
  { query: "How to find exposed secrets in client-side JavaScript", keyword: "exposed secrets in javascript" },
  { query: "How to prevent SQL injection in AI-generated code", keyword: "prevent sql injection ai code" },
  { query: "Is my Lovable.dev app leaking user data?", keyword: "lovable.dev data leak" },
  { query: "How to remove hardcoded secrets from v0 components", keyword: "hardcoded secrets v0" },
  { query: "OWASP Top 10 checklist for vibe-coded apps", keyword: "owasp top 10 vibe coding" },
  { query: "How to add input validation to AI-generated code", keyword: "input validation ai code" },
  { query: "Security checklist before launching a SaaS", keyword: "saas security checklist" },
  { query: "How to check npm dependencies for known CVEs", keyword: "check npm dependencies cve" },
  { query: "How to make your website appear in ChatGPT and Claude", keyword: "appear in chatgpt and claude" },
  { query: "How to add an llms.txt file to your website", keyword: "add llms.txt file" },
  { query: "What is Answer Engine Optimization (AEO)?", keyword: "what is answer engine optimization" },
  { query: "How to improve Core Web Vitals in a Next.js app", keyword: "improve core web vitals next.js" },
  { query: "How to add rate limiting to an indie SaaS API", keyword: "rate limiting saas api" },
  { query: "Do I need a security scan before deploying to Vercel?", keyword: "security scan before vercel deploy" },
  { query: "How should solo developers manage secrets and env vars?", keyword: "secrets management solo developer" },
  { query: "How to fix CORS misconfigurations in an API", keyword: "fix cors misconfiguration" },
  { query: "How to spot authentication bypass bugs in your app", keyword: "authentication bypass vulnerability" },
  { query: "Security scanning vs penetration testing: what's the difference?", keyword: "security scanning vs pentesting" },
  { query: "How an exposed .env file leads to account takeover", keyword: "exposed .env file risk" },
  { query: "How to prevent SSRF in AI-generated backend code", keyword: "prevent ssrf vulnerability" },
  { query: "How to add Content Security Policy headers to a Next.js app", keyword: "content security policy next.js" },
  { query: "How to secure webhook endpoints in a SaaS app", keyword: "secure webhook endpoints" },
  { query: "How to fix open redirect vulnerabilities in Next.js", keyword: "open redirect next.js" },
  { query: "Why AI coding tools skip security (and how to catch it)", keyword: "ai coding tools security risks" },
];

export async function generateBlogPost(): Promise<BlogPost | null> {
  await initBlogTable();

  const existingResult = await db.execute(`SELECT title, slug FROM blog_posts`);
  const existingTitles = existingResult.rows.map((r) => r.title as string);
  const existingHaystack = existingResult.rows
    .map((r) => `${r.title as string} ${r.slug as string}`.toLowerCase())
    .join(" || ");

  const usedTopics = existingTitles.join(", ");
  // De-dupe on the distinctive keyword (not the first few words, which collide
  // across many "how to…" queries) so we don't regenerate covered topics.
  const topicPool = BLOG_TOPICS.filter(
    (t) => !existingHaystack.includes(t.keyword.toLowerCase())
  );

  const suggestedTopic = topicPool.length > 0
    ? topicPool[Math.floor(Math.random() * topicPool.length)]
    : null;

  const content = await callDeepSeek([
    {
      role: "system",
      content: `You are an expert technical content writer for OverMCP (overmcp.com), a security scanning platform for "vibe-coded" apps — apps built quickly with AI coding tools like Cursor, Bolt.new, v0, Lovable, Replit Agent, etc.

Your audience: indie developers, solopreneurs, and makers who ship fast with AI but often skip security.

Write a blog post that:
1. Is 1000-1400 words
2. Directly and completely ANSWERS the search query it targets (this is what wins Google rankings and gets the post cited by ChatGPT/Claude/Perplexity)
3. Places the PRIMARY KEYWORD verbatim in: the title, the first 100 words, and at least one ## heading — naturally, never stuffed
4. Opens with a 2-3 sentence direct answer to the query (a "TL;DR" the searcher can act on immediately), then goes deeper
5. Provides genuine educational value: real examples, concrete code snippets, step-by-step fixes
6. Subtly positions OverMCP as the solution (mention it once, naturally — not salesy)
7. Uses markdown: ## headings, code blocks, bullet/numbered lists
8. ENDS with a "## FAQ" section containing 2-3 question/answer pairs (### Question then a short answer) — these win featured snippets and are easy for AI to extract
9. Includes a compelling meta title (under 60 chars) and meta description (under 155 chars), both containing the primary keyword

DO NOT write about topics already covered: ${usedTopics || "none yet"}

Return valid JSON:
{
  "title": "string (compelling, SEO-friendly, under 65 chars, contains the primary keyword)",
  "slug": "string (url-safe-kebab-case, derived from the primary keyword)",
  "excerpt": "string (1-2 sentences, hooks the reader, contains the primary keyword)",
  "content": "string (full markdown article, 1000-1400 words, ends with a ## FAQ section)",
  "tags": ["string", "string", "string"],
  "metaTitle": "string (under 60 chars, includes primary keyword)",
  "metaDescription": "string (under 155 chars, includes CTA)"
}`,
    },
    {
      role: "user",
      content: suggestedTopic
        ? `Write a blog post that answers this exact search query: "${suggestedTopic.query}"\nThe PRIMARY KEYWORD to target is: "${suggestedTopic.keyword}"`
        : `Write a blog post about a fresh security topic relevant to vibe-coded apps that hasn't been covered yet.`,
    },
  ]);
  if (!content) return null;

  const post = JSON.parse(content);
  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  await db.execute({
    sql: `INSERT INTO blog_posts (id, slug, title, excerpt, content, tags, meta_title, meta_description, published_at, created_at)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      id,
      post.slug,
      post.title,
      post.excerpt,
      post.content,
      JSON.stringify(post.tags || []),
      post.metaTitle || post.title,
      post.metaDescription || post.excerpt,
      now,
      now,
    ],
  });

  return {
    id,
    slug: post.slug,
    title: post.title,
    excerpt: post.excerpt,
    content: post.content,
    coverImage: null,
    tags: post.tags || [],
    metaTitle: post.metaTitle || post.title,
    metaDescription: post.metaDescription || post.excerpt,
    publishedAt: now,
    createdAt: now,
  };
}
