import { Octokit } from "octokit";

export interface RepoFile {
  name: string;
  path: string;
  content: string;
}

export function getOctokit(accessToken: string) {
  return new Octokit({
    auth: accessToken,
    request: {
      // Hard 20s timeout so GitHub API calls can't hang a request.
      fetch: (url: string | URL | Request, options?: RequestInit) =>
        fetch(url, { ...options, signal: AbortSignal.timeout(20_000) }),
    },
  });
}

const CODE_EXTENSIONS = [
  ".js", ".ts", ".tsx", ".jsx", ".py", ".html", ".css", ".vue",
  ".svelte", ".php", ".rb", ".go", ".rs", ".json", ".yaml", ".yml",
  ".env", ".sql", ".prisma", ".graphql", ".mjs", ".cjs",
];

const IGNORE_PATHS = [
  "node_modules", ".next", "dist", "build", ".git",
  "vendor", "__pycache__", ".vercel", "coverage",
];

export async function fetchRepoFiles(
  accessToken: string,
  owner: string,
  repo: string
): Promise<RepoFile[]> {
  const octokit = getOctokit(accessToken);
  const files: RepoFile[] = [];

  async function fetchDir(path: string) {
    if (files.length >= 20) return;

    const { data } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path,
    });

    if (!Array.isArray(data)) return;

    for (const item of data) {
      if (files.length >= 20) break;

      if (IGNORE_PATHS.some((p) => item.path.includes(p))) continue;

      if (item.type === "dir") {
        await fetchDir(item.path);
      } else if (item.type === "file") {
        const ext = "." + (item.name.split(".").pop()?.toLowerCase() || "");
        if (!CODE_EXTENSIONS.includes(ext)) continue;
        if ((item.size || 0) > 100000) continue;

        const { data: fileData } = await octokit.rest.repos.getContent({
          owner,
          repo,
          path: item.path,
        });

        if ("content" in fileData && fileData.content) {
          const content = Buffer.from(fileData.content, "base64").toString("utf-8");
          files.push({ name: item.name, path: item.path, content });
        }
      }
    }
  }

  await fetchDir("");
  return files;
}

export async function createFixPR(
  accessToken: string,
  owner: string,
  repo: string,
  fixes: { path: string; content: string }[]
): Promise<string> {
  const octokit = getOctokit(accessToken);

  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const baseSha = ref.object.sha;

  const branchName = `overmcp/fixes-${Date.now()}`;
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  for (const fix of fixes) {
    let existingSha: string | undefined;
    try {
      const { data: existing } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: fix.path,
        ref: branchName,
      });
      if ("sha" in existing) existingSha = existing.sha;
    } catch {
      // file doesn't exist yet
    }

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: fix.path,
      message: `fix: security patch for ${fix.path}`,
      content: Buffer.from(fix.content).toString("base64"),
      branch: branchName,
      ...(existingSha ? { sha: existingSha } : {}),
    });
  }

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: "🛡️ OverMCP: Security fixes & SEO improvements",
    body: `## Security Fixes Applied by OverMCP

This PR was automatically generated by [OverMCP](${process.env.NEXT_PUBLIC_APP_URL}) to fix security vulnerabilities and improve SEO in your codebase.

### Changes
${fixes.map((f) => `- Fixed \`${f.path}\``).join("\n")}

### What was fixed
- Security vulnerabilities (OWASP Top 10)
- SEO improvements
- Code quality enhancements

---
*Automated by OverMCP — Secure your vibe-coded apps*`,
    head: branchName,
    base: defaultBranch,
  });

  return pr.html_url;
}
