/**
 * High-intent commercial SEO landings.
 * Each page targets a money keyword, answers the query fully, and funnels
 * users to the free scanner — the primary ranking + conversion surface.
 */

export type SeoLanding = {
  slug: string;
  /** Primary keyword phrase (used in title, H1, first paragraph). */
  keyword: string;
  title: string;
  description: string;
  h1: string;
  /** 1–2 sentence direct answer for featured snippets / AI Overviews. */
  quickAnswer: string;
  heroSub: string;
  cta: string;
  ctaHref: string;
  sections: { heading: string; body: string[]; bullets?: string[] }[];
  faqs: { q: string; a: string }[];
  related: { href: string; label: string }[];
  priority?: number;
};

export const SEO_LANDINGS: SeoLanding[] = [
  {
    slug: "free-website-vulnerability-scanner",
    keyword: "free website vulnerability scanner",
    title: "Free Website Vulnerability Scanner — Scan Any URL in 30s",
    description:
      "Free website vulnerability scanner for AI-built apps. Find OWASP issues, leaked API keys, missing security headers, CVEs, and SEO risks. No signup required.",
    h1: "Free Website Vulnerability Scanner",
    quickAnswer:
      "A free website vulnerability scanner checks a live URL for security flaws such as exposed secrets, missing security headers, weak SSL, OWASP Top 10 risks, and known dependency CVEs — without installing software. OverMCP does this in about 30 seconds from a browser.",
    heroSub:
      "Paste any URL or public GitHub repo. Get OWASP findings, secret leaks, headers, SSL, SEO/AEO gaps, and dependency CVEs — free, no account.",
    cta: "Scan my site free",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "What a free website vulnerability scanner should check",
        body: [
          "Most free scanners only check a narrow slice (headers or SSL). A useful free website vulnerability scanner for modern apps should cover the risks that actually get AI-built products breached.",
        ],
        bullets: [
          "Exposed secrets and API keys in client-side JavaScript",
          "Missing or weak security headers (CSP, HSTS, X-Frame-Options)",
          "SSL/TLS certificate and protocol problems",
          "OWASP-style issues in HTML/JS (XSS sinks, open redirects, auth gaps)",
          "Outdated npm dependencies with known CVEs",
          "SEO, AEO, and GEO gaps that hurt Google and AI search visibility",
        ],
      },
      {
        heading: "Who this free scanner is built for",
        body: [
          "OverMCP is optimized for indie developers, solo founders, and agencies shipping apps built with Cursor, Bolt.new, v0, Lovable, Replit, Windsurf, and similar AI coding tools. Those stacks move fast — and often skip security reviews.",
          "You do not need a security team or a paid SAST license to run a pre-launch check. Paste the production URL, scan, and fix the highest-risk issues first.",
        ],
      },
      {
        heading: "How OverMCP’s free scan works",
        body: [
          "Enter a live website URL or a public GitHub repository. OverMCP crawls public assets, follows source maps when available, and runs parallel analyses for security, secrets, SEO/AEO, performance, and dependencies.",
          "The free tier shows your risk summary and issue preview. Paid Fix and Deploy tiers unlock full findings, code-level fixes, GitHub PRs, and optional one-click deploy.",
        ],
      },
      {
        heading: "Free website vulnerability scanner vs paid pentests",
        body: [
          "Automated free scans catch high-volume, known-pattern issues quickly. They do not replace a full penetration test for regulated products or complex multi-tenant backends.",
          "Use free scanning as a continuous gate before every deploy. Use a human pentester when you handle payments, health data, or enterprise contracts that require it.",
        ],
      },
    ],
    faqs: [
      {
        q: "Is there a truly free website vulnerability scanner?",
        a: "Yes. OverMCP lets you scan a public URL for free with no signup. You get a risk summary and preview findings. Deeper fix packages are optional paid upgrades.",
      },
      {
        q: "Can a free scanner find leaked API keys?",
        a: "OverMCP specifically looks for common secret patterns (OpenAI, Stripe, AWS, Firebase, JWTs, private keys) in client-side code and public repos — a frequent failure mode in vibe-coded apps.",
      },
      {
        q: "Does this work on Next.js and Vercel sites?",
        a: "Yes. Next.js, Vercel, Netlify, Cloudflare Pages, and Railway deployments are first-class targets, including apps generated by v0, Cursor, and Bolt.",
      },
      {
        q: "Will scanning my site break anything?",
        a: "No. Scans are read-only HTTP crawls of publicly reachable content. We do not exploit vulnerabilities or change your production data.",
      },
    ],
    related: [
      { href: "/website-security-checker", label: "Website security checker" },
      { href: "/ai-app-security-scanner", label: "AI app security scanner" },
      { href: "/tools/headers", label: "Security headers checker" },
      { href: "/tools/leak", label: "Secret leak scanner" },
      { href: "/blog", label: "Security guides" },
    ],
    priority: 1,
  },
  {
    slug: "website-security-checker",
    keyword: "website security checker",
    title: "Website Security Checker — Free Online Security Scan",
    description:
      "Free website security checker: scan any site for vulnerabilities, leaked secrets, SSL issues, security headers, and dependency CVEs. Built for AI-generated apps.",
    h1: "Website Security Checker",
    quickAnswer:
      "A website security checker is an online tool that reviews a site’s public configuration and code for common security weaknesses. OverMCP checks headers, SSL, secrets, OWASP-style risks, CVEs, and AI-search readiness from one free scan.",
    heroSub:
      "One free check for headers, SSL, secrets, OWASP risks, CVEs, and SEO/AEO — designed for sites shipped with AI coding tools.",
    cta: "Check my website free",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "Why run a website security checker before launch",
        body: [
          "Shipping fast with AI often means auth, CORS, env vars, and headers are incomplete. A website security checker catches those gaps while the fix cost is still low.",
        ],
        bullets: [
          "Stop leaked keys from hitting production traffic",
          "Confirm HTTPS and certificate validity",
          "Score security headers that block clickjacking and XSS",
          "Spot dependency CVEs before attackers do",
          "See SEO and AEO issues that limit Google and ChatGPT visibility",
        ],
      },
      {
        heading: "What OverMCP checks in one pass",
        body: [
          "Unlike single-purpose checkers, OverMCP combines security, secret detection, performance signals, and AI visibility into one report so you do not juggle five tools.",
          "Results are prioritized so you fix critical exposure first, then hardening, then polish.",
        ],
      },
      {
        heading: "Website security checker for vibe-coded apps",
        body: [
          "Apps from Cursor, Lovable, Bolt, and v0 often share the same failure patterns: service-role keys in the browser, open RLS policies, wildcard CORS, and missing CSP.",
          "OverMCP’s checks and blog guides are tuned to those patterns so the advice matches how your app was actually built.",
        ],
      },
    ],
    faqs: [
      {
        q: "How is a website security checker different from antivirus?",
        a: "Antivirus protects a device. A website security checker reviews your web app’s public surface — headers, certs, exposed secrets, and common web vulns — not malware on a laptop.",
      },
      {
        q: "Can I check a site I do not own?",
        a: "Only scan sites you own or have permission to test. OverMCP performs non-destructive, public-facing checks similar to what any visitor’s browser can see.",
      },
      {
        q: "How often should I re-check?",
        a: "Before every production deploy, and weekly for live products. OverMCP monitoring can re-scan on a schedule after you unlock the Deploy plan.",
      },
    ],
    related: [
      { href: "/free-website-vulnerability-scanner", label: "Free vulnerability scanner" },
      { href: "/tools/ssl", label: "SSL certificate checker" },
      { href: "/tools/headers", label: "Security headers checker" },
      { href: "/monitor", label: "Continuous monitoring" },
    ],
    priority: 0.95,
  },
  {
    slug: "ai-app-security-scanner",
    keyword: "AI app security scanner",
    title: "AI App Security Scanner for Cursor, Bolt, v0 & Lovable",
    description:
      "AI app security scanner for vibe-coded apps. Find OWASP issues, leaked keys, and deploy risks in apps built with Cursor, Bolt.new, v0, Lovable, and Replit.",
    h1: "AI App Security Scanner",
    quickAnswer:
      "An AI app security scanner reviews apps built with AI coding tools for the vulnerabilities those tools commonly introduce — leaked secrets, weak auth, missing headers, and insecure defaults — so you can ship vibe-coded products safely.",
    heroSub:
      "Built for Cursor, Bolt.new, v0, Lovable, Replit, Windsurf, and Copilot-generated apps. Free URL scan, optional auto-fix.",
    cta: "Scan my AI-built app",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "Why AI-generated apps need a dedicated scanner",
        body: [
          "AI coding tools optimize for “it works,” not “it is safe.” They hardcode keys, skip input validation, and leave Firebase or Supabase rules wide open unless you explicitly demand otherwise.",
          "Generic enterprise scanners miss vibe-coding patterns. OverMCP is tuned for AI-built web apps and the stacks they ship on.",
        ],
      },
      {
        heading: "Supported AI coding tools",
        body: ["Scan apps built with any of these — and more:"],
        bullets: [
          "Cursor and Claude-assisted codebases",
          "Bolt.new and StackBlitz-generated apps",
          "Vercel v0 UI + Next.js apps",
          "Lovable.dev full-stack apps",
          "Replit Agent and Replit-hosted apps",
          "Windsurf / Codeium and GitHub Copilot output",
        ],
      },
      {
        heading: "From scan to fix to deploy",
        body: [
          "Free scan: risk scores and preview issues. Fix ($5): full report, patches, SEO/AEO recommendations, GitHub PR. Deploy ($19): auto-deploy to Vercel, Netlify, Cloudflare, or Railway plus monitoring.",
        ],
      },
    ],
    faqs: [
      {
        q: "Is AI-generated code insecure by default?",
        a: "Not always — but it frequently omits authz checks, secret hygiene, and security headers. Treat AI code as untrusted until scanned.",
      },
      {
        q: "Can OverMCP fix issues automatically?",
        a: "Yes. The Fix tier can open a GitHub pull request with remediation. Deploy can push a fixed version to your host.",
      },
      {
        q: "Do you only support JavaScript apps?",
        a: "Public web apps (especially JS/TS, Next.js, React) are the primary focus because that is what most vibe-coding tools emit.",
      },
    ],
    related: [
      { href: "/cursor-security-scanner", label: "Cursor security scanner" },
      { href: "/vibe-coding-security", label: "Vibe coding security" },
      { href: "/free-website-vulnerability-scanner", label: "Free vulnerability scanner" },
      { href: "/blog", label: "AI security blog" },
    ],
    priority: 0.95,
  },
  {
    slug: "vibe-coding-security",
    keyword: "vibe coding security",
    title: "Vibe Coding Security — Scan & Fix AI-Built Apps",
    description:
      "Vibe coding security guide and free scanner. Catch XSS, SQL injection, leaked API keys, and misconfigurations in apps built by vibes — not security reviews.",
    h1: "Vibe Coding Security",
    quickAnswer:
      "Vibe coding security means hardening apps built quickly with AI tools so they do not ship with leaked secrets, broken access control, or missing browser protections. Scan early, fix high-risk issues, then automate rechecks.",
    heroSub:
      "You shipped on vibes. Now verify security before users (or attackers) do. Free scan for vibe-coded production apps.",
    cta: "Scan a vibe-coded app",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "What “vibe coding security” actually means",
        body: [
          "Vibe coding is building software by describing intent to an AI and iterating until the UI works. Security is often the last checkbox — or never a checkbox.",
          "A practical vibe coding security workflow is: generate → scan → fix critical paths → deploy → monitor. OverMCP automates the scan and fix steps.",
        ],
      },
      {
        heading: "Top risks in vibe-coded apps",
        body: [],
        bullets: [
          "API keys and service-role tokens embedded in frontend bundles",
          "Row Level Security / Firebase rules left open for “demo mode”",
          "XSS via dangerouslySetInnerHTML or unsanitized markdown",
          "Auth bypass when AI skips server-side session checks",
          "Wildcard CORS and missing rate limits on new API routes",
        ],
      },
      {
        heading: "A 15-minute pre-launch vibe coding security checklist",
        body: [
          "1) Run OverMCP on the production URL. 2) Rotate any leaked keys. 3) Lock database rules to per-user access. 4) Add security headers. 5) Re-scan after deploy.",
        ],
      },
    ],
    faqs: [
      {
        q: "Is vibe coding safe for production?",
        a: "It can be — if you add a security pass. Treat AI output like a junior developer’s PR: review, scan, and test auth paths before launch.",
      },
      {
        q: "What is the fastest way to improve vibe coding security?",
        a: "Remove secrets from the client, enforce server-side auth, set CSP/HSTS, and run an automated scan on every release.",
      },
    ],
    related: [
      { href: "/ai-app-security-scanner", label: "AI app security scanner" },
      { href: "/blog", label: "Vibe coding security blog" },
      { href: "/tools/leak", label: "Find leaked secrets" },
    ],
    priority: 0.9,
  },
  {
    slug: "cursor-security-scanner",
    keyword: "Cursor security scanner",
    title: "Cursor Security Scanner — Audit AI-Generated Code Fast",
    description:
      "Cursor security scanner for apps built with Cursor AI. Find leaked keys, OWASP issues, and deploy risks in Cursor-generated Next.js and full-stack code.",
    h1: "Cursor Security Scanner",
    quickAnswer:
      "A Cursor security scanner checks websites and repos produced with Cursor for common AI-code failures — secrets in source, missing validation, and weak headers — before you push to production.",
    heroSub:
      "Cursor ships features fast. OverMCP checks the security Cursor does not. Free URL or public GitHub scan.",
    cta: "Scan a Cursor app",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "Why Cursor projects need a security pass",
        body: [
          "Cursor agents write large patches quickly. Secrets end up in .env examples, client components, and committed config. Middleware and RLS policies are easy to skip when the prompt never mentions them.",
          "OverMCP gives Cursor users a one-click audit that maps to the stacks Cursor uses most: Next.js, React, Supabase, Firebase, Stripe, and OpenAI.",
        ],
      },
      {
        heading: "How to secure a Cursor-built app",
        body: [],
        bullets: [
          "Scan the live deploy URL with OverMCP",
          "Also scan the public GitHub repo for secrets history patterns",
          "Apply Fix PR recommendations for high-severity issues",
          "Add security headers on Vercel/Netlify before launch",
          "Re-scan after each major Cursor agent session",
        ],
      },
    ],
    faqs: [
      {
        q: "Does this integrate inside Cursor?",
        a: "OverMCP scans live URLs and public GitHub repos. Use it as your post-Cursor QA gate; optional GitHub PR fixes land back in the repo you edit in Cursor.",
      },
      {
        q: "Can I scan private Cursor projects?",
        a: "Scan any public URL. For private repos, connect GitHub where supported or deploy a preview URL and scan that.",
      },
    ],
    related: [
      { href: "/ai-app-security-scanner", label: "AI app security scanner" },
      { href: "/nextjs-security-scanner", label: "Next.js security scanner" },
      { href: "/blog", label: "Cursor security guides" },
    ],
    priority: 0.9,
  },
  {
    slug: "nextjs-security-scanner",
    keyword: "Next.js security scanner",
    title: "Next.js Security Scanner — Free Production Checklist Scan",
    description:
      "Next.js security scanner for App Router and Pages apps. Check headers, secrets, auth risks, and CVEs before you ship to Vercel.",
    h1: "Next.js Security Scanner",
    quickAnswer:
      "A Next.js security scanner audits a deployed Next.js app for leaked env vars, missing security headers, unsafe client patterns, dependency CVEs, and common App Router misconfigurations.",
    heroSub:
      "Built for Next.js on Vercel (and elsewhere). Catch the issues AI scaffolds usually miss — free scan, no install.",
    cta: "Scan my Next.js app",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "Next.js security issues we see most",
        body: [],
        bullets: [
          "NEXT_PUBLIC_ variables holding secret tokens",
          "Missing Content-Security-Policy and HSTS on Vercel",
          "Server Actions without auth checks",
          "Open redirects in middleware",
          "Vulnerable npm packages in package-lock.json",
        ],
      },
      {
        heading: "Pre-production Next.js security checklist",
        body: [
          "Run OverMCP against your preview URL, fix critical findings, add security headers in next.config or vercel.json, rotate any exposed keys, then re-scan production after promote.",
        ],
      },
    ],
    faqs: [
      {
        q: "Does this work with the App Router?",
        a: "Yes. We crawl the deployed site the same way users and bots do, which covers App Router and Pages Router deployments.",
      },
      {
        q: "Is this a static analysis tool?",
        a: "It is primarily a live-site and public-repo scanner with AI-assisted analysis, not a full offline SAST replacement.",
      },
    ],
    related: [
      { href: "/tools/headers", label: "Next.js security headers" },
      { href: "/free-website-vulnerability-scanner", label: "Free vulnerability scanner" },
      { href: "/connect/vercel", label: "Vercel security scanner" },
    ],
    priority: 0.9,
  },
  {
    slug: "api-key-leak-scanner",
    keyword: "API key leak scanner",
    title: "API Key Leak Scanner — Find Exposed Secrets Free",
    description:
      "Free API key leak scanner for websites and JS bundles. Detect exposed OpenAI, Stripe, AWS, Supabase, and Firebase keys before attackers do.",
    h1: "API Key Leak Scanner",
    quickAnswer:
      "An API key leak scanner searches public web assets and repositories for credential patterns that should never ship to browsers. OverMCP flags common provider keys and guides rotation.",
    heroSub:
      "Find OpenAI, Stripe, AWS, Supabase service_role, Firebase, and JWT material in client code — free specialized check plus full scan.",
    cta: "Scan for leaked keys",
    ctaHref: "/tools/leak",
    sections: [
      {
        heading: "Why API key leaks are the #1 vibe-coding incident",
        body: [
          "AI tools often paste keys into client components “to make the demo work.” Those keys ship in JS bundles and are scraped within minutes of going public.",
          "Use the dedicated secret leak tool for a fast check, then run the full OverMCP scan for related OWASP and header issues.",
        ],
      },
      {
        heading: "What to do if a key is already leaked",
        body: [],
        bullets: [
          "Revoke/rotate the key at the provider immediately",
          "Check provider logs for abuse",
          "Remove the key from git history if it was committed",
          "Move secrets to server-only env vars",
          "Re-scan to confirm the public surface is clean",
        ],
      },
    ],
    faqs: [
      {
        q: "Can Google find my leaked API keys?",
        a: "Search engines and automated scrapers both index public JS. Assume anything in a client bundle is public.",
      },
      {
        q: "Which keys does OverMCP look for?",
        a: "Common patterns for AWS, Stripe, OpenAI, Firebase, Supabase, private keys, and JWTs, among others.",
      },
    ],
    related: [
      { href: "/tools/leak", label: "Open secret leak scanner" },
      { href: "/free-website-vulnerability-scanner", label: "Full vulnerability scan" },
      { href: "/blog", label: "Secret leak guides" },
    ],
    priority: 0.88,
  },
  {
    slug: "answer-engine-optimization",
    keyword: "answer engine optimization",
    title: "Answer Engine Optimization (AEO) — Get Cited by AI Search",
    description:
      "What is Answer Engine Optimization (AEO)? Learn how to get cited by ChatGPT, Perplexity, and Google AI Overviews — plus free AEO checks in OverMCP.",
    h1: "Answer Engine Optimization (AEO)",
    quickAnswer:
      "Answer Engine Optimization (AEO) is the practice of structuring content so AI systems — ChatGPT, Claude, Perplexity, and Google AI Overviews — can understand, trust, and cite your pages when answering users.",
    heroSub:
      "AEO is SEO for the AI era. OverMCP audits AI bot access, structured data, llms.txt, and content citability.",
    cta: "Audit my site’s AEO free",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "AEO vs SEO vs GEO",
        body: [
          "SEO targets classic search rankings. AEO targets answer engines that synthesize responses. GEO (Generative Engine Optimization) overlaps with AEO and focuses on being included in generative answers with attribution.",
          "Winning strategy: clear answers near the top of pages, FAQ schema, llms.txt, accurate JSON-LD, and technical openness to AI crawlers.",
        ],
      },
      {
        heading: "How OverMCP helps AEO",
        body: [],
        bullets: [
          "Checks robots.txt for GPTBot, ClaudeBot, PerplexityBot, and others",
          "Flags missing llms.txt and structured data",
          "Scores content structure for AI comprehension",
          "Pairs AEO findings with security and performance so fixes ship together",
        ],
      },
    ],
    faqs: [
      {
        q: "Is AEO different from SEO?",
        a: "They share foundations (crawlability, expertise, clear structure) but AEO emphasizes quotable answers, schema, and AI crawler access more explicitly.",
      },
      {
        q: "Does OverMCP generate llms.txt?",
        a: "Deploy-tier workflows include AI visibility artifacts such as llms.txt guidance. You can also inspect OverMCP’s own /llms.txt as a reference.",
      },
    ],
    related: [
      { href: "/generative-engine-optimization", label: "What is GEO?" },
      { href: "/blog", label: "AEO / GEO guides" },
      { href: "/llms.txt", label: "Our llms.txt" },
    ],
    priority: 0.85,
  },
  {
    slug: "generative-engine-optimization",
    keyword: "generative engine optimization",
    title: "Generative Engine Optimization (GEO) — Rank in AI Answers",
    description:
      "What is Generative Engine Optimization (GEO)? Practical GEO tactics to appear in AI Overviews and chatbot answers. Free GEO-related audit with OverMCP.",
    h1: "Generative Engine Optimization (GEO)",
    quickAnswer:
      "Generative Engine Optimization (GEO) improves the odds that generative AI systems mention and cite your brand when they answer questions in your niche.",
    heroSub:
      "Get found in AI Overviews and chat answers with citable content, schema, and clean technical access for AI crawlers.",
    cta: "Run a free GEO-aware scan",
    ctaHref: "/#scan",
    sections: [
      {
        heading: "GEO tactics that work in 2026",
        body: [],
        bullets: [
          "Lead with a direct 2–3 sentence answer",
          "Use FAQ and HowTo schema where accurate",
          "Publish original examples and checklists, not recycled fluff",
          "Maintain llms.txt and allow reputable AI crawlers",
          "Earn topical authority with interconnected guides",
        ],
      },
      {
        heading: "GEO without sacrificing security",
        body: [
          "Opening your site to AI crawlers should not mean opening APIs to the world. OverMCP helps you balance visibility (AEO/GEO) with headers, secrets hygiene, and access control.",
        ],
      },
    ],
    faqs: [
      {
        q: "Is GEO the same as AEO?",
        a: "They are closely related. AEO emphasizes answer engines; GEO emphasizes generative inclusion. In practice, the same technical and content work helps both.",
      },
    ],
    related: [
      { href: "/answer-engine-optimization", label: "What is AEO?" },
      { href: "/ai-app-security-scanner", label: "AI app security scanner" },
      { href: "/blog", label: "GEO articles" },
    ],
    priority: 0.85,
  },
];

export function getSeoLanding(slug: string): SeoLanding | undefined {
  return SEO_LANDINGS.find((p) => p.slug === slug);
}

export function getAllSeoLandingSlugs(): string[] {
  return SEO_LANDINGS.map((p) => p.slug);
}
